### ISSUE TITLE
GTK 3.0 Port

### ISSUE THREAD

**Issue by thorsummoner** [forrestv/gdk-pixbuf-vtf#3]
Building on LinuxMint 17.2 (Gnome 3.10.8-8+quinta) yields errors indicating gnome 2.0 libs are missing:

```
gcc -Wall -std=c99 io-vtf.c  -o libpixbufloader-vtf.so \
        `pkg-config --cflags gtk+-2.0` \
        -shared -fpic -DGDK_PIXBUF_ENABLE_BACKEND -O3
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
io-vtf.c:28:38: fatal error: gdk-pixbuf/gdk-pixbuf-io.h: No such file or directory
 #include <gdk-pixbuf/gdk-pixbuf-io.h>
                                      ^

```

I would love a gnome3 port.

Heres the porting doc incase its helpful:
 https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html

---

If I were capable of perusing the port myself I would try, I do not yet grok C/C++ and do not feel capable of porting it myself. I do love Gnome and GTK, I'm familiar with them from the python gi.reposiory api; but that won't help here I feel.

If this was compatible and built on gnome 3 I would be happy to look into packaging it as a .deb, I have a little bit of experience with that and I have interest in learning the 'build from source' deb structure in contrast to the 'pack and install binary files' method I've done in the past.

**Comment by ChildishGiant** [comment]
That would be great

**Comment by Rahix** [comment]
I have been able to do the port. Go over to [my fork](https://github.com/Rahix/gdk-pixbuf-vtf) for the updated version.
